[package]
name = "uefi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r-efi = "4.0.0"
x86_64 = "0.14.8"
atomic_refcell = "0.1.3"
r-efi-alloc = "1.0.0"